name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start the server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '15s'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
        env:
          CI: true
